spring.application.name=flui3d-chat-backend
server.port=8090
ollama.api.url=http://127.0.0.1:11434
ollama.modelname.baseline=microfluidic_llama_3
ollama.modelname.reasoning=microfluidic_qwen3_reasoning
cors.allowed.origin=*
desyn.stl.timeout=320
desyn.gurobi.focus=0
desyn.gurobi.gap=0.02