spring.application.name=fluidllm-backend
server.port=8090
ollama.api.url=http://127.0.0.1:11434
ollama.modelname.baseline=flui3d_chat
ollama.modelname.reasoning=flui3d_chat_reasoning
cors.allowed.origin=*
desyn.stl.timeout=320
desyn.gurobi.focus=1
desyn.gurobi.gap=0.05
